services:
  php:
    image: php:8.1.18-fpm
    volumes:
      - type: bind
        source: $PWD/src
        target: /var/www/src
    networks:
      - nginx-network
  nginx:
    image: nginx:mainline-alpine3.17-slim
    ports:
      - "8080:80"
    networks:
      - nginx-network
    volumes:
      - type: bind
        source: $PWD/conf
        target: /etc/nginx/conf.d
      - type: bind
        source: $PWD/public
        target: /var/www/public

networks:
  nginx-network:
    driver: bridge